# Generated by Django 4.2.6 on 2023-10-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userget', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
